spring:
  application:
    name: cp-court-list-publishing-service

  # Disable SpringDoc auto-configuration
  autoconfigure:
    exclude: org.springdoc.core.configuration.SpringDocKotlinConfiguration
  config:
    import:
      - "optional:configtree:/mnt/secrets/rpe/"
      - "optional:classpath:application-datasource.yml"
      - "optional:classpath:application-server-management.yml"
      - "optional:classpath:application-azure.yml"
      - "optional:classpath:application-jwt.yml"
      - "optional:classpath:application-authz.yml"
      - "optional:classpath:application-audit.yml"
  threads:
    virtual:
      enabled: ${VIRTUAL_THREADS:false}

courtlistpublishing:
  system-user-id: ${COURTLISTPUBLISHING_SYSTEM_USER_ID:}

common-platform-query-api:
  base-url: ${CP_CLP_BASE_URL:http://localhost:8080}
  ssl:
    verify: ${COMMON_PLATFORM_QUERY_API_SSL_VERIFY:false}

public-court-list:
  enabled: ${PUBLIC_COURT_LIST_ENABLED:false}
  court-list-data:
    path: ${PUBLIC_COURT_LIST_DATA_PATH:}
    accept-header: ${PUBLIC_COURT_LIST_ACCEPT_HEADER:}

# Temporarily commented out due to SpringDoc compatibility issues with Spring Boot 4.0.0-M3
# springdoc:
#   packagesToScan: uk.gov.hmcts.cp.controllers
#   writer-with-order-by-keys: true