import uk.gov.moj.cpp.authz.drools.Outcome;
import uk.gov.moj.cpp.authz.drools.Action;

global uk.gov.moj.cpp.authz.http.providers.UserAndGroupProvider userAndGroupProvider;

rule "Allow LA – hearing"
when
  $o: Outcome()
  $a: Action(name == "courtlistpublishing-service.hearing")
  eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($a, "Legal Advisers","District Judge","System Users"))
then
  $o.setSuccess(true);
end

rule "Allow LA – files"
when
  $o: Outcome()
  $a: Action(name == "courtlistpublishing-service.files")
  eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($a, "Legal Advisers","District Judge","System Users"))
then
  $o.setSuccess(true);
end

