import uk.gov.moj.cpp.authz.drools.Outcome;
import uk.gov.moj.cpp.authz.drools.Action;

global uk.gov.moj.cpp.authz.http.providers.UserAndGroupProvider userAndGroupProvider;

rule "Allow – files"
when
  $o: Outcome()
  $a: Action(name == "courtlistpublishing-service.files")
  eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($a, "Legal Advisers","District Judge","System Users"))
then
  $o.setSuccess(true);
end

rule "Allow – court-list-publish"
when
  $o: Outcome()
  $a: Action(name == "courtlistpublishing-service.publish.post" ||
             name == "courtlistpublishing-service.publish.get")
  eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($a, "Legal Advisers","District Judge","System Users"))
then
  $o.setSuccess(true);
end

rule "Allow – public-court-list"
when
  $o: Outcome()
  $a: Action(name == "courtlistpublishing-service.public-court-list.get")
  eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($a, "Legal Advisers","District Judge","System Users"))
then
  $o.setSuccess(true);
end

